- hosts: k8s_cluster[0]
  tasks:
  - name: check param
    fail:
      msg: Cannot have both kubeconfig_localhost and create_oidc_kubeconfig set.
    when:
    - kubeconfig_localhost | default(false)
    - create_oidc_kubeconfig | default(false)

- hosts: k8s_cluster
  roles:
  - role: kubespray-defaults
    when:
    - create_oidc_kubeconfig
    - inventory_hostname == groups['kube_control_plane'][0]
  tasks:
  - name: Create OIDC kubeconfig
    when:
    - create_oidc_kubeconfig
    - inventory_hostname == groups['kube_control_plane'][0]
    block:
    - name: Get kubeconfig CA
      shell: "cat {{ kube_cert_dir }}/ca.crt | base64 --wrap 0"
      args:
        executable: /bin/bash
      register: ca_cert

    - name: Render templates for OIDC kubeconfig
      template:
        src: "kube_config_oidc.yml.j2"
        dest: "{{ kube_config_dir }}/{{ kubeconfig_file_name }}"
      register: oidc_kubeconfig

    - name: Copy OIDC kubeconfig to ansible host
      fetch:
        src: "{{ kube_config_dir }}/{{ kubeconfig_file_name }}"
        dest: "{{ artifacts_dir }}/"
        flat: yes
        validate_checksum: no
      become: no
      run_once: yes

  - name: "Generate kubeconfig"
    include_role:
      name: "kubernetes/client"
      tasks_from: main
    run_once: yes
    when:
      #- not final_admin_kubeconfig # Don't rerun the task if it already ran
      - kubeconfig_localhost
  - name: "Fetch kube adm config"
    ansible.builtin.copy:
      src: "{{ artifacts_dir }}/admin.conf"
      dest: "{{ artifacts_dir }}/{{ kubeconfig_file_name }}"
    delegate_to: localhost
    become: no
    run_once: yes
    when:
      - kubeconfig_localhost
  - name: "Remove admin.conf"
    ansible.builtin.file:
      state: absent
      path: "{{ artifacts_dir }}/admin.conf"
    run_once: yes
  - name: Ensure kubeconfig is encrypted
    ansible.builtin.shell: "source ../bin/common.bash && sops_encrypt {{ artifacts_dir }}/{{ kubeconfig_file_name }}"
    args:
      executable: /bin/bash
    delegate_to: localhost
    become: no
    run_once: yes
    when:
    - kubeconfig_localhost
